import type { Context } from 'hono'
import type { AppEnv } from './index'

type Verification = { status: string; verified: boolean; proof: string; chain_integrity: boolean; merkle_proof_valid: boolean; blockchain_anchor_valid: boolean; chain_position?: number; received_at?: string; network?: string; message: string }

export function renderVerificationPage(result: Verification): string {
  const ok = result.verified
  const accent = ok ? '#58b894' : result.status === 'pending_anchor' ? '#d7a84d' : '#d96d64'
  const title = ok ? 'VERIFIED' : result.status === 'pending_anchor' ? 'CHECKPOINT PENDING' : 'VERIFICATION FAILED'
  const symbol = ok ? '✓' : result.status === 'pending_anchor' ? '◷' : '×'
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Outside Docker — Verification</title><style>
  :root{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Helvetica Neue",sans-serif;color:#f2f0e9;background:#111612}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 85% 0%,#314c3d 0,#111612 42%);padding:48px 20px}.shell{max-width:720px;margin:auto}.brand{letter-spacing:.16em;text-transform:uppercase;font-size:12px;color:#a9b7a9}.mark{font-size:44px;font-weight:700;color:${accent};margin:62px 0 8px}.title{font-size:clamp(38px,8vw,72px);line-height:.95;letter-spacing:-.06em;margin:0 0 24px}.card{border:1px solid #405244;background:#182019cc;border-radius:24px;padding:28px;box-shadow:0 20px 80px #0005}.line{display:flex;justify-content:space-between;gap:20px;padding:14px 0;border-bottom:1px solid #334336}.line:last-child{border:0}.label{color:#91a395;font-size:13px}.value{text-align:right;word-break:break-all}.pill{display:inline-flex;padding:8px 12px;border-radius:99px;color:#0e1711;background:${accent};font-weight:700;font-size:12px}.note{color:#a9b7a9;line-height:1.6;font-size:14px;margin-top:24px}.footer{color:#718273;font-size:12px;margin-top:28px}@media print{body{background:#fff;color:#111}.card{border-color:#999;background:#fff;box-shadow:none}.brand,.label,.note,.footer{color:#555}}
  </style></head><body><main class="shell"><div class="brand">OUTSIDE DOCKER / EVIDENCE INTEGRITY</div><div class="mark">${symbol}</div><h1 class="title">${title}</h1><section class="card"><div class="line"><span class="label">PROOF</span><span class="value"><code>${escapeHtml(result.proof)}</code></span></div><div class="line"><span class="label">HASH CHAIN</span><span class="pill">${result.chain_integrity ? 'INTACT' : 'BROKEN'}</span></div><div class="line"><span class="label">MERKLE CHECKPOINT</span><span class="value">${result.merkle_proof_valid ? 'CONFIRMED' : 'PENDING'}</span></div><div class="line"><span class="label">POLYGON ANCHOR</span><span class="value">${result.blockchain_anchor_valid ? 'CONFIRMED' : 'PENDING'}</span></div>${result.chain_position ? `<div class="line"><span class="label">CHAIN POSITION</span><span class="value">${result.chain_position}</span></div>` : ''}${result.received_at ? `<div class="line"><span class="label">RECEIVED</span><span class="value">${escapeHtml(result.received_at)}</span></div>` : ''}</section><p class="note">${escapeHtml(result.message)}</p><p class="footer">OD proves receipt integrity and sequence after capture. It does not prove that the underlying record was truthful.</p></main></body></html>`
}

function escapeHtml(value: string): string { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;') }
export function renderLandingPage(): string {
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Outside Docker — Evidence Integrity</title><style>:root{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Helvetica Neue",sans-serif;color:#f2f0e9;background:#111612}body{margin:0;min-height:100vh;background:radial-gradient(circle at 70% -10%,#3e6750,#111612 50%);padding:32px 20px}.wrap{max-width:920px;margin:auto}.brand{font-size:12px;letter-spacing:.16em;color:#a9b7a9}.hero{padding:15vh 0 9vh;max-width:760px}.eyebrow{color:#8fd0a5;letter-spacing:.12em;text-transform:uppercase;font-size:13px}.hero h1{font-size:clamp(56px,11vw,126px);letter-spacing:-.08em;line-height:.86;margin:20px 0 30px}.hero p{font-size:clamp(20px,3vw,30px);line-height:1.25;color:#bdcbbd;max-width:680px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.item{padding:22px;border:1px solid #3a4d40;border-radius:20px;background:#172119cc}.num{color:#6dbb83;font-size:12px;letter-spacing:.1em}.item h2{font-size:20px;letter-spacing:-.03em}.item p{color:#91a395;line-height:1.5;font-size:14px}@media(max-width:680px){.grid{grid-template-columns:1fr}.hero{padding-top:12vh}}</style></head><body><main class="wrap"><div class="brand">OUTSIDE DOCKER</div><section class="hero"><div class="eyebrow">Event-chain integrity layer</div><h1>Keep the record.<br>Prove the sequence.</h1><p>Human evidence and machine logs, sealed into a chain that makes tampering visible without asking anyone to trust a dashboard.</p></section><section class="grid"><article class="item"><div class="num">01 / CAPTURE</div><h2>Receive</h2><p>Canonical payload hash with server receipt time. OD proves what it received—not whether the source was truthful.</p></article><article class="item"><div class="num">02 / LINK</div><h2>Sequence</h2><p>Every event links to the one before it. Deletion, insertion, mutation, and reorder leave a broken trail.</p></article><article class="item"><div class="num">03 / ANCHOR</div><h2>Checkpoint</h2><p>Merkle roots can be anchored to Polygon Amoy first, then independently checked by anyone with a proof.</p></article></section></main></body></html>`
}

export type { Verification }
